### ISSUE TITLE
Where does configuration need to go?

### ISSUE THREAD

**Issue by stuartlangridge** [Microsoft/ghcrawler-dashboard#24]
The README says that the bare minimum configuration is (some vars), but doesn't say where they should be *put*. `env/env.json`? `env.json`? `config/env.json`? Somewhere else?

**Comment by geneh** [comment]
I've updated the README:

> The variables may be set either individually as environment variables or in env.json file at the same level as the project (ghcrawler-dashboard/../env.json).

Thanks for looking into this!
